name: Build and Publish Kassa.Wpf

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore 

    - name: Build project
      run: dotnet build --configuration Release ./Kassa.Wpf/Kassa.Wpf.csproj

    - name: Test
      run: dotnet test --no-restore --logger  "trx;LogFileName=test-results.trx" || true

    - name: Test Report
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: DotNET Tests
        path: "**/test-results.trx"                            
        reporter: dotnet-trx
        fail-on-error: true

    - name: Publish project
      run: dotnet publish --configuration Release --output ./output ./Kassa.Wpf/Kassa.Wpf.csproj

    - name: Commit and Push binaries
      env:
        GITHUB_TOKEN: ${{ secrets.KASSA_TOKEN }}
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git fetch origin
        git checkout -b bin origin/bin || git checkout -b bin
        git rm -rf .
        Copy-Item -Path ./output/* -Destination . -Recurse
        Remove-Item -Recurse -Force -Path ./output
        git add .
        git commit -m "Add published binaries"
        git push -u origin bin --force
      shell: pwsh


      # Build and publish Kassa.Launcher
    - name: Build Kassa.Launcher project
      run: dotnet build --configuration Release ./Kassa.Launcher/Kassa.Launcher.csproj

    - name: Publish Kassa.Launcher project
      run: dotnet publish --configuration Release --output ./output-launcher -p:PublishSingleFile=true -p:PublishReadyToRun=true -r win-x64 -p:SelfContained=true ./Kassa.Launcher/Kassa.Launcher.csproj

    - name: Commit and Push Kassa.Launcher binaries
      env:
        GITHUB_TOKEN: ${{ secrets.KASSA_TOKEN }}
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git fetch origin
        git checkout -b launcher-bin origin/launcher-bin || git checkout -b launcher-bin
        git rm -rf .
        Copy-Item -Path ./output-launcher/* -Destination . -Recurse
        Remove-Item -Recurse -Force -Path ./output-launcher
        git add .
        git commit -m "Add published Kassa.Launcher binaries"
        git push -u origin launcher-bin --force
      shell: pwsh